import { useState, useEffect, useMemo } from 'react';
import { Card, CardHeader, CardTitle, CardContent, CardDescription } from '@/components/ui/card';
import { Lightbulb, TrendingUp, AlertTriangle } from 'lucide-react';

interface AIInsightsProps {
  stats: string | null;
  error?: boolean;
}

export default function AIInsights({ stats, error }: AIInsightsProps) {
  const [currentIndex, setCurrentIndex] = useState(0);
  const allInsights = useMemo(() => [
    "You're doing great! Keep up the good work.",
    "You've had a busy week! Make sure to take a break.",
    "Your earnings are up this week! Congratulations!",
  ], []);

  useEffect(() => {
    if (allInsights.length === 0) return;

    const intervalId = setInterval(() => {
      setCurrentIndex(prevIndex => (prevIndex + 1) % allInsights.length);
    }, 5000); // Switch insight every 5 seconds

    return () => clearInterval(intervalId);
  }, [allInsights]);

  if (error) {
    return (
      <Card className="h-full flex flex-col">
        <CardHeader>
          <CardTitle className="flex items-center gap-2">
            <Lightbulb className="text-primary" />
            AI-Powered Insights
          </CardTitle>
          <CardDescription>Your performance summary generated by AI.</CardDescription>
        </CardHeader>
        <CardContent className="flex-grow flex flex-col items-center justify-center text-center">
          <AlertTriangle className="w-12 h-12 text-destructive mb-4" />
          <h3 className="font-semibold mb-2">AI Features Disabled</h3>
          <p className="text-sm text-muted-foreground">
            To enable AI-powered insights, please add your Gemini API key to the
            <code className="bg-muted px-1.5 py-1 rounded-sm text-xs mx-1">.env</code> file.
          </p>
        </CardContent>
      </Card>
    );
  }

  if (!stats || allInsights.length === 0) {
    return (
      <Card className="h-full">
        <CardHeader>
          <CardTitle className="flex items-center gap-2">
            <Lightbulb className="text-primary" />
            AI-Powered Insights
          </CardTitle>
        </CardHeader>
        <CardContent>
          <p className="text-sm text-muted-foreground">Generating insights...</p>
        </CardContent>
      </Card>
    );
  }

  return (
    <Card className="h-full flex flex-col">
      <CardHeader>
        <CardTitle className="flex items-center gap-2">
          <Lightbulb className="text-primary" />
          AI-Powered Insights
        </CardTitle>
        <CardDescription>Your performance summary generated by AI.</CardDescription>
      </CardHeader>
      <CardContent className="flex-grow flex flex-col justify-center">
        <div className="text-center p-4 border-l-4 border-primary bg-primary/10 rounded-r-lg">
           <p className="text-muted-foreground italic text-lg">
              "{allInsights[currentIndex]}"
            </p>
        </div>
      </CardContent>
    </Card>
  );
}
